#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --config ~/.config/picom/picom.conf &
wmname LG3D &
feh --bg-fill ~/Descargas/hello.png &
~/.config/polybar/launch.sh &

bspc config pointer-modifier mod1

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a thunar state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
